name: agilapp
description: A minimal Flutter app scaffold created by Copilot
publish_to: 'none'
version: 0.1.0+1
environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  google_fonts: ^5.0.0
  dio: ^5.0.0
  flutter_secure_storage: ^8.0.0
  flutter_staggered_grid_view: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
